//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordReviewLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CodeId { get; set; }
        public string UserId { get; set; }
        public int CommentId { get; set; }
        public string Contents { get; set; }
    
        public virtual User User { get; set; }
    }
}
