//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordReviewLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int CodeId { get; set; }
        public int Number { get; set; }
        public byte[] CodeText { get; set; }
        public string Description { get; set; }
    
        public virtual Code Code { get; set; }
    }
}
